### ISSUE TITLE
some Indonesian subtitles not found

### ISSUE THREAD

**Issue by nexusdiscord** [Stremio/stremio-opensubtitles#14]
I watching movie name "Public Enemies" and no subtitle for Indonesian language, when I trying search on Opensubtitles.org I found it

**Comment by TRtomasz** [comment]
There are multiple things why you might not be able to see subtitles in stremio.
1. Cache, subtitles are too new and we didnt have time to cache them.
2. Subtitles format is other than srt and we do not support other formats
3. Video hash didn't much subtitles hash so in other words subtitles were created for other video file than one you were trying to watch.

**Comment by TRtomasz** [comment]
@nexusdiscord we checked addon again and indeed it looks like we had an issue with it. it should be fixed soon :)
