### ISSUE TITLE
Fallback for no subtitles found

### ISSUE THREAD

**Issue by nulam** [Stremio/stremio-opensubtitles#22]
As far as I understand, the search for subtitles works based on movie hash matching. 

I think it'd be a good idea to attempt a search by stream name / filename (without the extension) for when no subtitles are found.

**Comment by TRtomasz** [comment]
we use two queries one for hash one for imdbID, there is no need for the third one. https://github.com/Stremio/stremio-opensubtitles/blob/master/lib/find.js#L258
