### ISSUE TITLE
Serbian subtitles missing

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-opensubtitles#24]
The addon doesn't show Serbian subtitles for some movies and series
![Screenshot_2023-01-18-00-19-37-594_com miui securitycenter](https://user-images.githubusercontent.com/18757054/213033663-6ed82645-4367-4519-b57e-add7f3a8e44f.jpg)
![Screenshot_2023-01-18-00-19-42-331_com stremio one](https://user-images.githubusercontent.com/18757054/213033666-82925916-efaf-429c-9e8e-e6db18b3783f.jpg)

**Comment by TRtomasz** [comment]
Subtitles are provided by addon which takes them from opensubtitles. IF there are no matching subs on opensubtitles then they will not be displayed.
