### ISSUE TITLE
Better URL handling

### ISSUE THREAD

**Issue by core1024** [Stremio/stremio-opensubtitles#7]
At the moment we parse the URL in the `rewriteUrl` function with regular expressions.
Much better approach would be by using the `URL` and `URLSearchParams` objects.

**Comment by Ivshti** [comment]
I'm not sure this is needed since we want to migrate to https://github.com/stremio/stremio-opensubtitlesv2. It's taking time since opensubtitles has to make the JSON API official.

**Comment by core1024** [comment]
Closing as currently we are using node 8 and these objects are not added yet
